---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: backstage
    repoURL: https://backstage.github.io/charts
    targetRevision: 1.2.0
    helm:
      releaseName: backstage
      parameters:
        - name: backstage.image.registry
          value: c8n.io
        - name: backstage.image.repository
          value: vfarcic/backstage
        - name: ingress.enabled
          value: "true"
          forceString: true
        - name: ingress.className
          value: traefik
        - name: ingress.host
          value: backstage.212.2.246.192.nip.io
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
