---
apiVersion: v1
kind: Namespace
metadata:
  name: backstage
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage
  namespace: backstage
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      postInitSQL:
        - ALTER ROLE app CREATEDB
