---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: backstage
    repoURL: https://backstage.github.io/charts
    targetRevision: 1.2.0
    helm:
      releaseName: backstage
      parameters:
        - name: backstage.image.registry
          value: ghcr.io
        - name: backstage.image.repository
          value: guymenahem/backstage/backstage-argocd-workshop
        - name: backstage.image.tag
          value: "1.0.2"
        - name: ingress.enabled
          value: "traefik"
        - name: ingress.className
          value: backstage.212.2.243.227.nip.io
        - name: ingress.host
          value: backstage.212.2.240.248.nip.io
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
