# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "backstage-rw"
  CATALOG_LOCATION: "https://github.com/guymenahem/backstage-demo/catalog/app-component.yaml"
  BASE_URL: ""
  ARGOCD_URL: ""
